# Compiler
CC = g++

# Compiler flags
CFLAGS = -Wall -Wextra -std=c++11

# Source files
SRCS = Dummy.cpp parce.c

# Object files
OBJS = $(SRCS:.cpp=.o)

# Executable name
TARGET = myprogram

# Default target
all: $(TARGET)

parce: parce.c
	$(CC) $(CFLAGS) -o parce parce.c

# Compile source files into object files
%.o: %.cpp
	$(CC) $(CFLAGS) -c $< -o $@

# Link object files into executable
$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) $^ -o $@

# Clean up object files and executable
clean:
	rm -f $(OBJS) $(TARGET)